---

- hosts: servers
  become: yes

  vars_files: vars/errors.yml


  tasks:
    - name: Install ntp
      yum:
        name: ntp
        state: present
      register: result
      ignore_errors: yes

    - name: display error message if task failed
      debug: 
        msg: "{{ result.msg }}"
      when: result.failed

    - import_tasks: tasks/epel-repo.yml
      when: result.msg == epel_error

    - name: Make sure ntp is installed 
      service:
        name: ntpd
        state: started
        enabled: yes

      

